qsub command.sh ACC
qsub command.sh BLCA
qsub command.sh BRCA
qsub command.sh CESC
qsub command.sh CHOL
qsub command.sh COAD
qsub command.sh DLBC
qsub command.sh ESCA
qsub command.sh GBM
qsub command.sh HNSC
qsub command.sh KICH
qsub command.sh KIRC
qsub command.sh KIRP
qsub command.sh LAML
qsub command.sh LGG
qsub command.sh LIHC
qsub command.sh LUAD
qsub command.sh LUSC
qsub command.sh MESO
qsub command.sh OV
qsub command.sh PAAD
qsub command.sh PCPG
qsub command.sh PRAD
qsub command.sh READ
qsub command.sh SARC
qsub command.sh SKCM
qsub command.sh STAD
qsub command.sh TGCT
qsub command.sh THCA
qsub command.sh THYM
qsub command.sh UCEC
qsub command.sh UCS
qsub command.sh UVM

